-- https://sqliteonline.com/

WITH PREP_SET AS (
  SELECT DISTINCT TO_CHAR(date_trunc('MONTH',"date"::TIMESTAMP), 'YYYY/MM/DD') AS MONTHLY_DATE
    , COUNT(VALUE) OVER (PARTITION BY TO_CHAR(date_trunc('MONTH',"date"::TIMESTAMP), 'YYYY/MM/DD')) AS CURR_MONTH_COUNT
from out_3 as posts
  )
 SELECT MONTHLY_DATE
 	, CURR_MONTH_COUNT
    -- FORMULA:
    -- Percent Change = 100 × (Present or Future Value – Past or Present Value) / Past or Present Value
 	, 100 * TRUNC((CURR_MONTH_COUNT - LAG(CURR_MONTH_COUNT,1) OVER (ORDER BY MONTHLY_DATE))::NUMERIC / LAG(CURR_MONTH_COUNT,1) OVER (ORDER BY MONTHLY_DATE)::NUMERIC,1) as PERCENT_GROWTH
 FROM PREP_SET
 ORDER BY MONTHLY_DATE ASC